# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /share/ryes/Vivado/VivadoProjects/trusthub_pynq_z1/trusthub_pynq_z1.srcs/sources_1/ip/state_memory/state_memory.xci
# IP: The module: 'state_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /share/ryes/Vivado/VivadoProjects/trusthub_pynq_z1/trusthub_pynq_z1.gen/sources_1/ip/state_memory/state_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_memory'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /share/ryes/Vivado/VivadoProjects/trusthub_pynq_z1/trusthub_pynq_z1.srcs/sources_1/ip/state_memory/state_memory.xci
# IP: The module: 'state_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /share/ryes/Vivado/VivadoProjects/trusthub_pynq_z1/trusthub_pynq_z1.gen/sources_1/ip/state_memory/state_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'state_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
