# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /share/ryes/Vivado/Constraints/PYNQ-Z1_C.xdc

# IP: ip/out_memory/out_memory.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==out_memory || ORIG_REF_NAME==out_memory} -quiet] -quiet
